---
######################################
# These Values can be the all.yml or in a group specific yml
# and should generally be fine with their defaults.
######################################
# The below details will be used to create a virtual multicast network tunnel
# (and optionally a bridge) to allow microcloud locate other servers with mDNS reliably.

# ip of subnet where multicast will work.
# if unsure, use the subnet of the main private network
lookup_subnet: 192.168.0.1/24 # bridge start ip subnet (preferably don't start with .0)

# if servers don't share a common interface name
# you can override this for each server's host_vars
lookup_bridge: mcbr_bridge # only alphanumbric and underscore

# lookup_bridge_mac_prefix: '52:54:00'
# # `ovn_uplink_interface` is optional and represents the name of the interface
# # that will be created and reserved for use with OVN
ovn_uplink_interface: eth9
vlan: vlan0
# ovn_uplink_subnet: 192.168.32.1/20

# location where various packages will be installed
package_dir: /usr/bin

# be careful with the hannelvalues, ensure they are correct
# or the setup will fail without a proper indication as to why
snapd_channel: latest/stable
ngrok_channel: v3/stable
core_channel: latest/stable
lxd_channel: 5.21/stable
microceph_channel: reef/stable
microovn_channel: 22.03/stable
microcloud_channel: latest/edge
openvswitch_channel: latest/edge

# wipe volumes assigned to local or ceph before using
wipe_local: true
wipe_ceph: true

extra_apt_binaries:
  - vim
  - dosfstools
  - open-iscsi
  # - tcpflow
  # - make
  # - jq
  # - build-essential
  # - acl
  # - libacl1-dev
  # - libcap-dev
  # - liblxc1
  # - liblxc-dev
  # - libsqlite3-dev
  # - libudev-dev
  # - libuv1-dev
  # - libdqlite-dev
extra_snap_binaries: []
  # - name: go
  #   channel: latest/stable
  #   classic: true
# `ovn` is optional and represents the OVN & uplink network configuration for LXD.
# honestly, I don't thinnk you'd need it
# ovn:
#   ipv4_gateway: 192.0.2.1/24
#   ipv4_range: 192.0.2.100-192.0.2.254
#   ipv6_gateway: 2001:db8:d:200::1/64
#   dns_servers: 192.0.2.1,2001:db8:d:200::1