---

######################################
# Values you're probably interested in changing.
######################################
# ansible_ssh_host_key_checking: False
# your environments, eg. dev, test, uat, sit, prod etc.
groups: # can only be in all.yml
  - dev
######################################


######################################
# Values here can be the all.yml or in a group specific yml
# and should generally be fine with their defaults.
######################################

# dummy interface that should be created
# for microcloud to use
ovn_uplink_interface: eth9
ovn_uplink_mac_prefix: '52:54:00'
# location where various packages will be installed
package_dir: /usr/bin

# be careful with these values, ensure they are correct
# or the setup will fail without a proper indication as to why
lxd_channel: 5.21/stable
microceph_channel: quincy/stable
microovn_channel: 22.03/stable
microcloud_channel: latest/stable

# wipe volumes assigned to local or ceph before using
wipe_local: true
wipe_ceph: true

# `ovn` is optional and represents the OVN & uplink network configuration for LXD.
# ovn:
#   ipv4_gateway: 192.0.2.1/24
#   ipv4_range: 192.0.2.100-192.0.2.254
#   ipv6_gateway: 2001:db8:d:200::1/64
#   dns_servers: 192.0.2.1,2001:db8:d:200::1