---
- hosts: all
  become: true
  gather_facts: true
  # the tags are very important as they might
  # be specified by the user when running the
  # taskfile eg. task "list-init-dev" or task run-install-dev 
  roles:
    - role: microcloud-prerequisites
      tags: [init]
    - role: microcloud-install
      tags: [install]
    - role: update-cache
      tags: [cache]
    - role: rollback
      tags: [rollback]