# will be auto-populated
sit:
  children:
    self_hosted:
      hosts:
        192.168.0.144:
          # provider: baremetal
          # ceph_volume_path: /dev/mmcblk0p1
          hostname: homelabnode1
          index_key: 2
          ipv4_address: 192.168.0.144 # [mandatory]
          ipv4_address_iface: eno0
          ipv4_address_private: 192.168.0.144 # [mandatory]
          ipv4_address_private_iface: eno0
          local_volume_path: /dev/mmcblk0
        192.168.0.145: # public IP
          # provider: baremetal
          # ceph_volume_path: /dev/sda1
          hostname: orangepi4-lts-1
          index_key: 0
          ipv4_address: 192.168.0.145
          ipv4_address_iface: eth0
          ipv4_address_private: 192.168.0.145
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sda
        192.168.0.147:
          # provider: baremetal
          ceph_volume_path: /dev/sda
          hostname: orangepi4-lts-0
          index_key: 1
          ipv4_address: 192.168.0.147
          ipv4_address_iface: eth0
          ipv4_address_private: 192.168.0.147
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/mmcblk0
test:
  children:
    azure:
      hosts:
        138.91.192.183:
          ceph_volume_path: /dev/sdc
          hostname: micro-vm-0
          index_key: 0
          ipv4_address: 138.91.192.183
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.5
          ipv4_address_private_cidr: 10.0.0.5/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdd
          provider: azure
        138.91.195.63:
          ceph_volume_path: /dev/sdc
          hostname: micro-vm-1
          index_key: 1
          ipv4_address: 138.91.195.63
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.6
          ipv4_address_private_cidr: 10.0.0.6/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdd
          provider: azure
        40.78.24.91:
          ceph_volume_path: /dev/sdc
          hostname: micro-vm-2
          index_key: 2
          ipv4_address: 40.78.24.91
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.4
          ipv4_address_private_cidr: 10.0.0.4/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdd
          provider: azure
