# will be auto-populated
dev:
  children:
    self_hosted:
      hosts:
        192.168.0.145: # public IP
          hostname: orangepi4-lts
          ipv4_address_private: "192.168.0.145/24" # [mandatory]
        192.168.0.147: # public IP
          hostname: orangepi800
          ipv4_address_private: "192.168.0.147/24" # [mandatory]
