dev:
  hosts:
    192.168.0.145:

other_env:
  hosts:
    example.com:


# # This is the default ansible 'hosts' file.
# #
# # It should live in your Git repository, and there should be a link from /etc/ansible/hosts:
# #   /etc/ansible/hosts -> /path/to/myAnsibleProject/hosts
# #
# #   - Comments begin with the '#' character
# #   - Blank lines are ignored
# #   - Groups of hosts are delimited by [header] elements
# #   - You can enter hostnames or ip addresses
# #   - A hostname/ip can be a member of multiple groups

# [anygroup]
# server1     ansible_host=192.168.0.1
# server2     ansible_host=192.168.0.2
# server3     ansible_host=192.168.0.3
# server4     ansible_host=192.168.0.4

# # Add your own groups here. Hosts can be added to multiple groups like so:
# # [anothergroup]
# # server[1:3]
# # anotherserver     ansible_host=192.168.0.10
