# will be auto-populated
dev:
  children:
    digital_ocean:
      hosts:
        104.131.186.76:
          ceph_volume_path: null
          hostname: micro-droplet-1
          index_key: 1
          ipv4_address: 104.131.186.76
          ipv4_address_private: 10.108.0.2
          ipv4_address_private_cidr: 10.108.0.2/20
          local_volume_path: null
        45.55.64.209:
          ceph_volume_path: null
          hostname: micro-droplet-2
          index_key: 2
          ipv4_address: 45.55.64.209
          ipv4_address_private: 10.108.0.3
          ipv4_address_private_cidr: 10.108.0.3/20
          local_volume_path: null
        45.55.74.76:
          ceph_volume_path: null
          hostname: micro-droplet-0
          index_key: 0
          ipv4_address: 45.55.74.76
          ipv4_address_private: 10.108.0.4
          ipv4_address_private_cidr: 10.108.0.4/20
          local_volume_path: null
