# will be auto-populated
dev:
  children:
    digital_ocean:
      hosts:
        159.203.162.71:
          ceph_volume_path: null
          hostname: micro-droplet-0
          index_key: 0
          ipv4_address: 159.203.162.71
          ipv4_address_private: 10.108.0.2/20
          local_volume_path: null
        45.55.75.26:
          ceph_volume_path: null
          hostname: micro-droplet-1
          index_key: 1
          ipv4_address: 45.55.75.26
          ipv4_address_private: 10.108.0.3/20
          local_volume_path: null
