# will be auto-populated
test:
  children:
    azure:
      hosts:
        20.12.0.118:
          ceph_volume_path: /dev/sdc
          hostname: micro-vm-0
          index_key: 0
          ipv4_address: 20.12.0.118
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.4
          ipv4_address_private_cidr: 10.0.0.4/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdd
        20.12.0.124:
          ceph_volume_path: /dev/sdc
          hostname: micro-vm-1
          index_key: 1
          ipv4_address: 20.12.0.124
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.5
          ipv4_address_private_cidr: 10.0.0.5/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdd
        20.12.0.36:
          ceph_volume_path: /dev/sdc
          hostname: micro-vm-2
          index_key: 2
          ipv4_address: 20.12.0.36
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.6
          ipv4_address_private_cidr: 10.0.0.6/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdd
