# will be auto-populated
test:
  children:
    azure:
      hosts:
        172.200.40.166:
          ceph_volume_path: /dev/sdd
          hostname: micro-vm-1
          index_key: 1
          ipv4_address: 172.200.40.166
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.5
          ipv4_address_private_cidr: 10.0.0.5/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdc
        172.200.41.132:
          ceph_volume_path: /dev/sdd
          hostname: micro-vm-0
          index_key: 0
          ipv4_address: 172.200.41.132
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.6
          ipv4_address_private_cidr: 10.0.0.6/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdc
        172.200.41.144:
          ceph_volume_path: /dev/sdd
          hostname: micro-vm-2
          index_key: 2
          ipv4_address: 172.200.41.144
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.4
          ipv4_address_private_cidr: 10.0.0.4/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdc
