# will be auto-populated
sit:
  children:
    self_hosted:
      hosts:
        192.168.0.144:
          # provider: baremetal
          ceph_volume_paths:
            - path: /dev/sda
              wipe: true
          hostname: homelabnode1
          index_key: 0
          ipv4_address: 192.168.0.144 # [mandatory]
          ipv4_address_iface: eno0
          ipv4_address_private: 192.168.0.144 # [mandatory]
          ipv4_address_private_iface: eno0
          local_volume_path: /dev/mmcblk0
          lookup_bridge: eno0
        192.168.0.145: # public IP
          # provider: baremetal
          ceph_volume_paths:
            - path: /dev/sda
              wipe: true
          hostname: orangepi4-lts-1
          index_key: 1
          ipv4_address: 192.168.0.145
          ipv4_address_iface: eth0
          ipv4_address_private: 192.168.0.145
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdb
          lookup_bridge: eth0
        192.168.0.147:
          # provider: baremetal
          ceph_volume_paths:
            - path: /dev/sda
              wipe: true
          hostname: orangepi4-lts-0
          index_key: 2
          ipv4_address: 192.168.0.147
          ipv4_address_iface: eth0
          ipv4_address_private: 192.168.0.147
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/mmcblk0
          lookup_bridge: eth0
