# will be auto-populated
test:
  children:
    azure:
      hosts:
        172.172.44.61:
          ceph_volume_path: /dev/sdd
          hostname: micro-vm-2
          index_key: 2
          ipv4_address: 172.172.44.61
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.5
          ipv4_address_private_cidr: 10.0.0.5/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdc
        172.172.47.31:
          ceph_volume_path: /dev/sdd
          hostname: micro-vm-1
          index_key: 1
          ipv4_address: 172.172.47.31
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.6
          ipv4_address_private_cidr: 10.0.0.6/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdc
        172.177.243.60:
          ceph_volume_path: /dev/sdd
          hostname: micro-vm-0
          index_key: 0
          ipv4_address: 172.177.243.60
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.4
          ipv4_address_private_cidr: 10.0.0.4/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdc
