# will be auto-populated
sit:
  children:
    self_hosted:
      hosts:
        # when trying to identify ips, you can use this comand
        # ip addr show <interface_name> | grep 'inet ' | awk '{print $2}' | head -n 1
        192.168.0.51:
          # provider: baremetal
          # ceph_volume_paths:
          #   - path: /dev/sda
          #     wipe: true
          hostname: homelabnode1
          # do not repeat an index key!!!
          index_key: 0
          ipv4_address: 192.168.0.51 # [mandatory]
          ipv4_address_iface: eno0
          ipv4_address_private: 192.168.0.51 # [mandatory]
          ipv4_address_private_iface: eno0
          local_volume_path: /dev/mmcblk0
          lookup_bridge: eno0
        192.168.0.52: # public IP
          # provider: baremetal
          # ceph_volume_paths:
          #   - path: /dev/sda
          #     wipe: true
          hostname: homelabnode2
          index_key: 1
          ipv4_address: 192.168.0.52
          ipv4_address_iface: enP4p65s0
          ipv4_address_private: 192.168.0.52
          ipv4_address_private_iface: enP4p65s0
          local_volume_path: /dev/sda
          lookup_bridge: enP4p65s0
        192.168.0.53: # public IP
          # provider: baremetal
          # ceph_volume_paths:
          #   - path: /dev/sda
          #     wipe: true
          hostname: homelabnode3
          index_key: 2
          ipv4_address: 192.168.0.53
          ipv4_address_iface: enP4p65s0
          ipv4_address_private: 192.168.0.53
          ipv4_address_private_iface: enP4p65s0
          local_volume_path: /dev/sda
          lookup_bridge: enP4p65s0
