# will be auto-populated
test:
  children:
    azure:
      hosts:
        104.46.192.248:
          ceph_volume_path: /dev/sdd
          hostname: micro-vm-2
          index_key: 2
          ipv4_address: 104.46.192.248
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.6
          ipv4_address_private_cidr: 10.0.0.6/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdc
        40.65.200.46:
          ceph_volume_path: /dev/sdd
          hostname: micro-vm-0
          index_key: 0
          ipv4_address: 40.65.200.46
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.5
          ipv4_address_private_cidr: 10.0.0.5/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdc
        40.65.205.109:
          ceph_volume_path: /dev/sdc
          hostname: micro-vm-1
          index_key: 1
          ipv4_address: 40.65.205.109
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.4
          ipv4_address_private_cidr: 10.0.0.4/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdd
