# will be auto-populated
dev:
  children:
    digital_ocean:
      hosts:
        161.35.191.33:
          ceph_volume_path: null
          hostname: micro-droplet-0
          index_key: 0
          ipv4_address: 161.35.191.33
          ipv4_address_private: 10.108.0.3
          ipv4_address_private_iface: eth1
          local_volume_path: null
        161.35.191.37:
          ceph_volume_path: null
          hostname: micro-droplet-2
          index_key: 2
          ipv4_address: 161.35.191.37
          ipv4_address_private: 10.108.0.4
          ipv4_address_private_iface: eth1
          local_volume_path: null
        64.225.55.22:
          ceph_volume_path: null
          hostname: micro-droplet-1
          index_key: 1
          ipv4_address: 64.225.55.22
          ipv4_address_private: 10.108.0.2
          ipv4_address_private_iface: eth1
          local_volume_path: null
