# will be auto-populated
sit:
  children:
    self_hosted:
      hosts:
        192.168.0.145: # public IP
          ceph_volume_path: /dev/sda1
          hostname: orangepi4-lts
          index_key: 0
          ipv4_address: 192.168.0.145
          ipv4_address_iface: eth0
          ipv4_address_private: 192.168.0.145
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sda2
        192.168.0.147:
          ceph_volume_path: /dev/mmcblk0p1
          hostname: orangepi4-lts
          index_key: 1
          ipv4_address: 192.168.0.147
          ipv4_address_iface: eth0
          ipv4_address_private: 192.168.0.147
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/mmcblk0p2
          # 192.168.0.144:
          #   hostname: orangepi800
          #   index_key: 2
          #   ipv4_address: 192.168.0.144 # [mandatory]
          #   ipv4_address_iface: eno0
          #   ipv4_address_private: 192.168.0.144 # [mandatory]
          #   ipv4_address_private_iface: eno0
