# will be auto-populated
dev:
  children:
    self_hosted:
      hosts:
        64.18.0.0:
          ipv4_address_private: "192.168.20.50"
          # local_volume_path:
          # ceph_volume_path:
        64.18.0.1:
          ipv4_address_private: "192.168.20.51"
    digital_ocean:
      hosts:
        104.131.2.176:
          ipv4_address_private: "10.108.0.2"
        174.138.80.96:
          ipv4_address_private: "10.108.0.3"
        174.138.88.126:
          ipv4_address_private: "10.108.0.4"
