# will be auto-populated
test:
  children:
    azure:
      hosts:
        52.167.200.44:
          ceph_volume_path: /dev/sdd
          hostname: micro-vm-1
          index_key: 1
          ipv4_address: 52.167.200.44
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.6
          ipv4_address_private_cidr: 10.0.0.6/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdc
        52.167.200.49:
          ceph_volume_path: /dev/sdd
          hostname: micro-vm-2
          index_key: 2
          ipv4_address: 52.167.200.49
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.5
          ipv4_address_private_cidr: 10.0.0.5/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdc
        52.167.207.21:
          ceph_volume_path: /dev/sdd
          hostname: micro-vm-0
          index_key: 0
          ipv4_address: 52.167.207.21
          ipv4_address_iface: eth0
          ipv4_address_private: 10.0.0.4
          ipv4_address_private_cidr: 10.0.0.4/16
          ipv4_address_private_iface: eth0
          local_volume_path: /dev/sdc
