# will be auto-populated
dev:
  children:
    digital_ocean:
      hosts:
        104.131.71.94:
          ceph_volume_path: /dev/sdb
          hostname: micro-droplet-1
          index_key: 1
          ipv4_address: 104.131.71.94
          ipv4_address_private: 10.108.0.2
          ipv4_address_private_cidr: 10.108.0.2/20
          local_volume_path: /dev/sda
        134.209.173.50:
          ceph_volume_path: /dev/sda
          hostname: micro-droplet-0
          index_key: 0
          ipv4_address: 134.209.173.50
          ipv4_address_private: 10.108.0.3
          ipv4_address_private_cidr: 10.108.0.3/20
          local_volume_path: /dev/sdb
        134.209.45.231:
          ceph_volume_path: /dev/sdb
          hostname: micro-droplet-2
          index_key: 2
          ipv4_address: 134.209.45.231
          ipv4_address_private: 10.108.0.4
          ipv4_address_private_cidr: 10.108.0.4/20
          local_volume_path: /dev/sda
