# ipv4_address: 20.12.0.118
# hostname: micro-vm-0
# bridge_ipv4_cidr: 192.168.0.1/20
# ipv4_address: 20.12.0.118
# hostname: micro-vm-0
# bridge_ipv4_cidr: 192.168.0.1/20
network:
  version: 2
  renderer: networkd
  bridges:
    mcbr_bridge:
      dhcp4: true
      dhcp6: false
      interfaces: [tunnel_01, tunnel_02]
      addresses: ['192.168.0.1/20']
      macaddress: 60:45:bd:84:05:24
      openvswitch:
        protocols: [OpenFlow10, OpenFlow11, OpenFlow12]
        controller:
          addresses: ['unix:/var/run/openvswitch/mcbr_bridge.mgmt']
          connection-mode: out-of-band
        fail-mode: secure
        mcast-snooping: true
        external-ids:
          iface-id: micro-vm-0
        other-config:
          disable-in-band: true
  tunnels:
    tunnel_01:
      mode: vxlan
      id: '01'
      link: 'eth0'
      remote: "10.0.0.5"
      local: "10.0.0.4"
      port: 4789
      mac-learning: false
      mtu: 8950
    tunnel_02:
      mode: vxlan
      id: '02'
      link: 'eth0'
      remote: "10.0.0.6"
      local: "10.0.0.4"
      port: 4789
      mac-learning: false
      mtu: 8950
