---
# Add further tasks for the common role (applied to all servers) to this playbook...

# - name: Set index based on inventory hostname
#   set_fact:
#     index: "{{ ansible_play_hosts.index(inventory_hostname) | int }}"

- name: delete interface bridge {{ lookup_bridge }}
  command: ip link delete {{ lookup_bridge }}
  ignore_errors: true

- name: lxc network delete {{ lookup_bridge }}
  command: lxc network delete {{ lookup_bridge }}
  ignore_errors: true

- name: delete interface bridge {{ lookup_bridge }}
  command: ip link delete {{ lookup_bridge }}
  ignore_errors: true


- name: Delete vxlan tunnels (all-to-all)
  command: ip link delete {{ iface_name }}
  vars:
    iface_name: vxlan_{{ index_key }}_{{ hostvars[item]['index_key'] }}
  loop: "{{ groups[ansible_limit] }}"
  when: inventory_hostname != item
  ignore_errors: true

- name: Delete gretap tunnels (all-to-all)
  command: ip link delete {{ iface_name }}
  vars:
    iface_name: gretap_{{ index_key }}_{{ hostvars[item]['index_key'] }}
  loop: "{{ groups[ansible_limit] }}"
  when: inventory_hostname != item
  ignore_errors: true


- name: Delete "{{ ovn_uplink_interface }}" interface
  command: ip link delete {{ ovn_uplink_interface }}
  ignore_errors: true

- name: Delete preseed file location
  run_once: true
  command: rm infra-{{ansible_limit}}/preseed.yml
  ignore_errors: true
