---

- name: Uninstall Microceph snap
  # when: "'microceph' not in ansible_facts.packages"
  snap:
    name: microceph
    state: absent

- name: Uninstall Microovn snap
  # when: "'microovn' not in ansible_facts.packages"
  snap:
    name: microovn
    state: absent

- name: Uninstall Microcloud snap
  # when: "'microcloud' not in ansible_facts.packages"
  snap:
    name: microcloud
    state: absent
  
- name: UnInstall LXD snap
  # when: "'lxd' not in ansible_facts.packages"
  snap:
    name: lxd
    state: absent

- name: Save netplan in remote host
  file:
    path: '{{ dest_netplan_file }}'
    state: absent
  vars:
    dest_netplan_file: /etc/netplan/10{{index_key}}-microcloud.yaml

- name: Unconditionally reboot the machine with all defaults
  ansible.builtin.reboot:
