# list of environment variables that needs to be set for this
# terraform module to work properly
required_env:
  - DO_PAT

# single command or chained command that can be applied to the provider's tfstate file
# to extract and output comma separated list of IPs from it.
# eg.: 0.0.0.1,0.0.0.2,0.0.0.3

# the output will be exported as an environment variable
# with a name in this format: {{.GROUP}}_{{.PROVIDER}}_ips
# eg. dev_digital_ocean_ips
# So consider variables of this format as reserved
get-ips: |
  yq '.resources[] |
    select(.type == "digitalocean_droplet") |
    .instances[].attributes |
    [pick(["ipv4_address","ipv4_address_private"])]'