# list of environment variables that needs to be set for this
# terraform module to work properly

# always prefix it with TF_VAR so it can automatically
# be picked up by terraform
required_env:
  - TF_VAR_tenancy_ocid
  - TF_VAR_user_ocid
  - TF_VAR_fingerprint
  - TF_VAR_private_key_path
  - TF_VAR_region