---
- name: Gather the package facts
  package_facts:
    manager: auto

- name: Refresh all snaps
  snap:
    state: refreshed

- name: Install LXD snap (channel - {{lxd_channel}})
  when: "'lxd' not in ansible_facts.packages"
  snap:
    name: lxd
    channel: '{{lxd_channel}}'
    classic: no  # Avoid classic confinement (recommended)

- name: Install Microceph snap (channel - '{{microceph_channel}}')
  when: "'microceph' not in ansible_facts.packages"
  snap:
    name: microceph
    channel: '{{microceph_channel}}'
    classic: no

- name: Install MicroOVN snap (channel - '{{microovn_channel}}')
  when: "'microovn' not in ansible_facts.packages"
  snap:
    name: microovn
    channel: '{{microovn_channel}}'
    classic: no

- name: Install Microcloud snap (channel - '{{microcloud_channel}}')
  when: "'microcloud' not in ansible_facts.packages"
  snap:
    name: microcloud
    channel: '{{microcloud_channel}}'
    classic: no

- name: Initialize microcloud (only on first host)
  when: inventory_hostname == ansible_play_hosts[0]
  command: echo to-do
