---
- name: Check if the resolved.conf exists
  stat:
    path: /etc/systemd/resolved.conf
  register: resolved_stat

- name: Install Microceph snap
  # when: "'microceph' not in ansible_facts.packages"
  snap:
    name: microceph
    channel: "{{microceph_channel | default('reef/stable') }}"
    classic: false
  register: install_status
  retries: 3
  delay: 3
  until: install_status is succeeded
  

- name: Install Microovn snap
  # when: "'microovn' not in ansible_facts.packages"
  snap:
    name: microovn
    channel: '{{microovn_channel}}'
    classic: no
  register: install_status
  retries: 3
  delay: 3
  until: install_status is succeeded

- name: Install Microcloud snap
  # when: "'microcloud' not in ansible_facts.packages"
  snap:
    name: microcloud
    channel: '{{microcloud_channel}}'
    classic: no
  register: install_status
  retries: 3
  delay: 3
  until: install_status is succeeded

- name: Reboot
  ansible.builtin.reboot:
  when: var_provider != "azure"


- name: Check if secondary ip exists on {{ipv4_address_iface}}
  shell: |
    ip addr show {{ipv4_address_iface}} | grep "inet " | awk '{print $2}' | {
        read -r ip1
        read -r ip2
        if [ -n "$ip2" ]; then
            echo "$ip2"
        fi
    }
  register: secondary_ip

- name: Delete secondary ip
  command: ip addr del {{ secondary_ip.stdout }} dev {{ipv4_address_iface}}
  when: secondary_ip.stdout != ""

# - name: Ping test all-to-all network connectivity
#   when: var_provider != ""
#   command: |-
#     ping -c 2 {{ ip_dest }}
#   vars:
#     index_key: "{{ hostvars[item]['index_key'] }}"
#     ip_dest: '{{ lookup_subnet | ansible.utils.next_nth_usable(index_key | int) }}'
#   loop: "{{ groups[ansible_limit] }}"
#   register: ping_results
#   retries: 3
#   delay: 3
#   until: ping_results.rc == 0

# - name: Temporarily enable per-link MulticastDNS for {{ lookup_bridge }}
#   command: resolvectl mdns {{ lookup_bridge }} yes
#   when: resolved_stat.stat.exists

# - name: Test mDNS all-to-all connectivity
#   command: resolvectl query -4 {{peer_hostname}}.local
#   vars:
#     peer_hostname: "{{hostvars[item]['ansible_nodename']}}"
#   loop: "{{ groups[ansible_limit] }}"
#   register: mDNS_results
#   retries: 3
#   delay: 3
#   until: mDNS_results.rc == 0
#   when: resolved_stat.stat.exists

- name: Copy preseed file to first host
  delegate_to: '{{ansible_play_hosts[0]}}'
  run_once: true
  copy:
    src: ./infra-{{ansible_limit}}/preseed.yml
    dest: /tmp/infra-{{ansible_limit}}-preseed.yml
  when: use_preseed is not defined or use_preseed == true

- name: Initialize microcloud (only on first host)
  delegate_to: '{{ansible_play_hosts[0]}}'
  run_once: true
  shell:
    cmd: >-
      cat /tmp/infra-{{ansible_limit}}-preseed.yml |
      microcloud init --preseed --debug --verbose
    # cmd: >-
    #   cat /tmp/infra-{{ansible_limit}}-preseed.yml |
    #   microcloud init --address {{address}}
    #   --preseed --debug --verbose
    # --state-dir /var/snap/microcloud/common/state
  register: init_result
  ignore_errors: true
  vars:
    address: '{{ lookup_subnet | ansible.utils.next_nth_usable(index_key | int) }}'
  when: use_preseed is not defined or use_preseed == true
- debug:
    msg: '{{init_result}}'
  run_once: true
  when: init_result is defined

- name: Show LXC Cluster
  when: init_result is defined and init_result.changed == true
  delegate_to: '{{ansible_play_hosts[0]}}'
  run_once: true
  command: lxc cluster list
  register: lxc_cluster
- debug:
    msg: "{{lxc_cluster.stdout_lines}}"
  run_once: true
  ignore_errors: true

- name: Show Next Steps
  delegate_to: '{{ansible_play_hosts[0]}}'
  run_once: true
  debug:
    msg: >-
      use_preseed is set to false, you'll need
      to run 'microcloud init'on any of the servers
  when: use_preseed is defined and use_preseed != true