---
# Add further tasks for the common role (applied to all servers) to this playbook...

- name: Gather the package facts
  package_facts:
    manager: auto

- name: Update package lists
  apt: update_cache=yes
  # tags: ["prerequisite"]

- name: Install snapd package
  when: "'snapd' not in ansible_facts.packages"
  apt:
    name: snapd
    state: present
  # tags: ["prerequisite"]

- name: Install core snap
  when: "'snapd' not in ansible_facts.packages"
  snap:
    name: core
    state: present
  # tags: ["prerequisite"]

- name: Install kmod package
  when: "'kmod' not in ansible_facts.packages"
  apt:
    name: kmod
    state: present
  # tags: ["prerequisite"]

- name: Install macchanger package
  when: "'macchanger' not in ansible_facts.packages"
  apt:
    name: macchanger
    state: present
  # tags: ["prerequisite"]

- name: Load dummy kernel module
  modprobe:
    name: dummy
  # tags: ["prerequisite"]

- name: Create dummy interface {{ ovn_uplink_interface }}
  command: ip link add {{ ovn_uplink_interface }} type dummy
  args:
    creates: /sys/class/net/{{ ovn_uplink_interface }}
  # tags: ["prerequisite"]

- name: Delete {{ ovn_uplink_interface }}
  command: ip link delete {{ ovn_uplink_interface }}
  # tags: ["prerequisite"]

- name: Show interface {{ ovn_uplink_interface }} information (for informational purposes only)
  debug:
    msg: |-
      f"Interface {{ ovn_uplink_interface }} details: {{ ansible_{ovn_uplink_interface} }}"
    
  # tags: ["prerequisite"]
