---
# Add further tasks for the common role (applied to all servers) to this playbook...

- name: Gather the package facts
  package_facts:
    manager: auto
# - name: Set index based on inventory hostname
#   set_fact:
#     index: "{{ ansible_play_hosts.index(inventory_hostname) | int }}"
# - name: Generate random MAC address with prefix
#   set_fact:
#     random_mac: "{{ lookup_bridge_mac_prefix | community.general.random_mac }}"
# - name: Print the package facts
#   ansible.builtin.debug:
#     var: ansible_facts.packages
#   # tags: ["prerequisite"]
# - name: Show interface
#   debug:
#     msg: "{{ anible_facts['mcbr_bridge'] }}"
    # msg: "{{ hostvars[host]['ansible_facts']['eth1']['ipv4']['address'] }}"
# - name: Show interfaces
#   debug:
#     msg: "{{ ansible_interfaces }}"

# - name: Get loaded modules
#   register: loaded_modules
#   command: lsmod

###### Uncomment this
- name: Update package lists
  apt: update_cache=yes

- name: Install snapd package
  when: "'snapd' not in ansible_facts.packages"
  apt:
    name: snapd
    state: present

- name: Set snapd version
  # when: "'snapd' not in ansible_facts.packages"
  # snap:
  #   name: snapd
  #   state: present
  #   channel: '{{snapd_channel}}'
  command: snap refresh snapd --channel={{snapd_channel}}

- name: Install core snap
  when: "'snapd' not in ansible_facts.packages"
  snap:
    name: core
    state: present
  # tags: ["prerequisite"]

- name: Install bridge-utils
  when: "'bridge-utils' not in ansible_facts.packages"
  apt:
    name: bridge-utils
    state: present

- name: Install net-tools
  when: "'net-tools' not in ansible_facts.packages"
  apt:
    name: net-tools
    state: present
    # update_cache: yes

- name: Install network-manager
  when: "'network-manager' not in ansible_facts.packages"
  apt:
    name: network-manager
    state: present

- name: Check if secondary ip exists on eth0
  shell: |
    ip addr show eth0 | grep "inet " | awk '{print $2}' | {
        read -r ip1
        read -r ip2
        if [ -n "$ip2" ]; then
            echo "$ip2"
        fi
    }
  register: secondary_ip
# - debug:
#     msg: secondary ip - {{secondary_ip.stdout}}

- name: Delete secondary ip
  command: ip addr del {{ secondary_ip.stdout }} dev eth0
  when: secondary_ip.stdout != ""

# - name: Check if bridge already exists
#   command: |
#     lxc network show {{ lookup_bridge }}
#   register: bridge_check
#   ignore_errors: true

- name: Create lxc bridge interface {{ lookup_bridge }}
  # delegate_to: '{{ansible_play_hosts[0]}}'
  # run_once: true
  when: vars["ansible_" + lookup_bridge] is not defined
  # when: bridge_check.rc != 0
  command: >-
    lxc network create {{ lookup_bridge }}
    ipv4.address={{ lookup_subnet |
    ansible.utils.next_nth_usable(host_index | int) }}/{{ bridge_netmask }}
    ipv4.nat=true
    ipv6.nat=true
  # command: brctl addbr {{ lookup_bridge }}
  args:
    creates: /sys/class/net/{{ lookup_bridge }}
  vars:
    bridge_netmask: "{{ lookup_subnet | ansible.utils.ipaddr('prefix')}}"
    host_index: "{{ index_key }}"

# - name: Set default FORWARD policy to DROP in ebtables
#   command: ebtables -P FORWARD DROP

# - name: Create gre tunnels (all-to-all)
#   command: >-
#     ip link add {{peer_grename | sort | join()}} type gretap
#     local {{ ipv4_address_private }}
#     remote {{ hostvars[item]['ipv4_address_private'] }}
#   vars:
#     peer_grename: "gre-{{ index_key }}{{ hostvars[item]['index_key'] }}"
#   args:
#     creates: /sys/class/net/{{peer_grename | sort | join()}}
#   loop: "{{ groups[ansible_limit] }}"
#   when: inventory_hostname != item
   
# - name: Bridge gre tunnels (all-to-all)
#   command: brctl addif {{ lookup_bridge }} {{peer_grename | sort | join()}}
#   vars:
#     peer_grename: "gre-{{ index_key }}{{ hostvars[item]['index_key'] }}"
#   args:
#     creates: /sys/class/net/{{peer_grename | sort | join()}}
#   loop: "{{ groups[ansible_limit] }}"
#   when: >-
#     (vars["ansible_" + peer_grename] is not defined
#     or vars["ansible_" + peer_grename].active != true)
#     and inventory_hostname != item

# - name: Bring up tunnels (all-to-all)
#   command: ip link set dev {{peer_grename | sort | join()}} up
#   vars:
#     peer_grename: "gre-{{ index_key }}{{ hostvars[item]['index_key'] }}"
#   loop: "{{ groups[ansible_limit] }}"
#   when: >-
#     (vars["ansible_" + peer_grename] is not defined
#     or vars["ansible_" + peer_grename].active != true)
#     and inventory_hostname != item

- name: Create lxc gre tunnels (all-to-all)
  shell: |-
    # lxc network set {{ lookup_bridge }} bridge.hwaddr {{random_mac}}
    lxc network set {{ lookup_bridge }} tunnel.{{peer_grename | sort | join()}}.protocol gre
    lxc network set {{ lookup_bridge }} tunnel.{{peer_grename | sort | join()}}.id {{peer_grename | sort | join()}}
    # lxc network set {{ lookup_bridge }} tunnel.{{peer_grename | sort | join()}}.interface eth1
    # lxc network set {{ lookup_bridge }} tunnel.{{peer_grename | sort | join()}}.port 4789
    lxc network set {{ lookup_bridge }} tunnel.{{peer_grename | sort | join()}}.local {{ ipv4_address_private }}
    lxc network set {{ lookup_bridge }} tunnel.{{peer_grename | sort | join()}}.remote {{ hostvars[item]['ipv4_address_private'] }}
  vars:
    iface_id: "1{{ index_key }}{{ hostvars[item]['index_key'] }}"
    peer_hostname: "{{hostvars[item]['ansible_nodename']}}"
    peer_grename: "1{{ index_key }}{{ hostvars[item]['index_key'] }}"
    random_mac: "{{ lookup_bridge_mac_prefix | community.general.random_mac }}"
  args:
    creates: /sys/class/net/{{ lookup_bridge }}-{{ peer_grename }}
  loop: "{{ groups[ansible_limit] }}"
  when: inventory_hostname != item and vars["ansible_" + lookup_bridge + "-" + peer_grename] is not defined
  #   vars["ansible_" + iface_name] is not defined
  #   and inventory_hostname != item


- name: Ping test all-to-all network connectivity
  command: |-
    ping -c 2 {{ lookup_subnet | ansible.utils.next_nth_usable(host_index | int) }}
  vars:
    host_index: "{{ hostvars[item]['index_key'] }}"
  loop: "{{ groups[ansible_limit] }}"
  # when: inventory_hostname != item
  register: ping_results
  retries: 3
  delay: 3
  until: ping_results.rc == 0

# - name: Test that ping tests passed
#   fail:
#     msg: "Ping test failed: {{item.stdout_lines}}"
#   when: item.rc != 0
#   loop: "{{ping_results.results}}"

- name: Create ovn_uplink_interface veth pair {{ ovn_uplink_interface }} and {{ ovn_uplink_interface }}p
  command: ip link add {{ ovn_uplink_interface }} type veth peer name {{ ovn_uplink_interface }}p
  args:
    creates: /sys/class/net/{{ ovn_uplink_interface }}
  when: vars["ansible_" + ovn_uplink_interface] is not defined

- name: Add ovn_uplink_interface {{ ovn_uplink_interface }} to bridge {{ lookup_bridge }}
  command: ip link set {{ ovn_uplink_interface }}p master {{ lookup_bridge }}
  when: >-
    (vars["ansible_" + ovn_uplink_interface] is not defined
    or vars["ansible_" + ovn_uplink_interface].active != true)

- name: Bring "{{ ovn_uplink_interface }}" interface up
  command: ip link set dev {{ ovn_uplink_interface }} up
  when: >-
    (vars["ansible_" + ovn_uplink_interface] is not defined
    or vars["ansible_" + ovn_uplink_interface].active != true)

- name: Bring "{{ ovn_uplink_interface }}p" interface up
  command: ip link set dev {{ ovn_uplink_interface }}p up
  when: >-
    (vars["ansible_" + ovn_uplink_interface] is not defined
    or vars["ansible_" + ovn_uplink_interface].active != true)

# - name: Show interface {{ ovn_uplink_interface }} information (for informational purposes only)
#   when: 
#     - vars["ansible_" + ovn_uplink_interface] is defined
#   debug:
#     msg: |-
#       f"Interface {{ ovn_uplink_interface }} is active: {{ vars['ansible_' + ovn_uplink_interface].active }}"
#   # tags: ["prerequisite"]

- name: Set preseed file location
  run_once: true
  debug:
    msg: infra-{{ansible_limit}}/preseed.yml
  register: preseed_file

- name: add lookup_subnet and interface to preseed.yml using private ip subnet
  delegate_to: localhost
  run_once: true
  when: inventory_hostname == ansible_play_hosts[0]
  shell: |-
    touch {{preseed_file.msg}}
    yq -i '.lookup_subnet = "{{ lookup_subnet | ansible.utils.next_nth_usable(host_index | int) }}/{{ bridge_netmask }}" |
    .lookup_interface = "{{ lookup_bridge }}"' {{preseed_file.msg}}
  become: false
    # yq -i '.lookup_subnet = "{{ ipv4_address_private_cidr }}" |
  vars:
    bridge_netmask: "{{ lookup_subnet | ansible.utils.ipaddr('prefix')}}"
    host_index: "{{ hostvars[inventory_hostname]['index_key'] }}"

- name: Set ovn config
  when: ovn is defined
  run_once: true
  local_action: command yq -i --prettyPrint '.ovn = env(ovn)' {{preseed_file.msg}}
  environment:
    ovn: "{{ovn}}"
  become: false

- name: Remove ovn config
  when: ovn is not defined
  run_once: true
  local_action: command yq -i --prettyPrint 'del(.ovn)' {{preseed_file.msg}}
  become: false
  
# - name: Get remote hostname
#   debug:
#     msg: "{{ ansible_hostname }}"
#   register: current_remote

- name: Set microcloud system config
  delegate_to: localhost
  throttle: 1 # make it run serially per remote host
  # take the existing 'systems:' field if it exists and
  # remove any object with the same name as this current host
  # then add the details of the current host(essentally replacing)
  command: >-
    yq -i --prettyPrint 'del(.systems[] | select(.name == "{{ansible_nodename}}")) |
    .systems += [{"name": "{{ansible_nodename}}",
    "ovn_uplink_interface": "{{ovn_uplink_interface}}",
    "storage": env(host_storage)}]'
    {{preseed_file.msg}}
  vars:
    storage:
      local:
        path: '{{local_volume_path | default("")}}'
        wipe: '{{wipe_local}}'
      ceph:
        - path: '{{ceph_volume_path | default("")}}'
          wipe: '{{wipe_ceph}}'
    # current_remote: '{{current_remote}}'
  environment:
    host_storage: '{{storage}}'
  become: false

- name: Remove empty entries from preseed
  delegate_to: localhost
  command: >-
    yq --inplace 'with(.systems.[];
      (select(.storage.local.path == "")) |= del(.storage.local) |
      (select(.storage.ceph[]?.path == "")) |= del(.storage.ceph)|
      del(.. | select(tag == "!!map" and length == 0)))'
    {{preseed_file.msg}}
  become: false



    
